[project]
name = "neurotype"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "ipywidgets>=8.1.7",
    "matplotlib>=3.10.3",
    "nibabel>=5.3.2",
    "notebook>=7.4.2",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "scipy>=1.15.3",
]
